### ISSUE TITLE
MLH banner is wack on mobile version dimensions

### ISSUE THREAD

**Issue by jvssicawu** [nwplus/nwhacks2020#20]
Refer to images below: 

MLH banner is either floating off or is cut off by screen boundary: 
[![Image from Gyazo](https://i.gyazo.com/4b7b088d94c8d5042757121e76a25772.jpg)](https://gyazo.com/4b7b088d94c8d5042757121e76a25772)
[![Image from Gyazo](https://i.gyazo.com/d46ae174f898d19aee2172e271cc3ca7.jpg)](https://gyazo.com/d46ae174f898d19aee2172e271cc3ca7)

other details:
- using MacBook Pro 13-inch

**Comment by Ciuffi** [comment]
fixed by https://github.com/nwplus/nwhacks2020/commit/644130446ab5e3f9c06c107c4f4c830eba4a257b

**Comment by jvssicawu** [comment]
Doesn't seem to have been fixed?  [![Image from Gyazo](https://i.gyazo.com/16284340362f4061d2100f61b68474fa.jpg)](https://gyazo.com/16284340362f4061d2100f61b68474fa)

**Comment by jvssicawu** [comment]
if its easier we can remove the banner from mobile dimensions

**Comment by Ciuffi** [comment]
I think it just hadn't been deployed yet
