### ISSUE TITLE
minor issues

### ISSUE THREAD

**Issue by jvssicawu** [nwplus/nwhacks2020#28]
- [ ] FAQ questions text should be bold and can we shorten the length of the faqs like how they look on Figma?
- [x] the titles of each section should be bold! "nwHacks 2019 Recap", "FAQ", "Sponsors"
- [x] when scrolling down to the team section photo, while the image loads it creates a whitespace lag(?) like a box of white space, anyway we can make that disappear
- [x] can we make sure the question "What is a hackathon?" appears as the top/first item on the General category FAQ? seems weird to have it in the middle when that's a good starter question that people might have. if anything, i would keep the ordering the same as last year's FAQs
- [x] we should fix the Cloudsploit sponsor image too cuz its glitchy but that might be a spocos problem

**Comment by Ciuffi** [comment]
We're working on the team section whitespace by converting everything to png so its smaller/quicker to load.

Regarding cloudsploit, yeah thats on spocos.

**Comment by Ciuffi** [comment]
We don't have an easy way to sort FAQ's yet, I put what is a hackathon? at the top for now, but i'll figure out a good sorting technique later.

**Comment by ianmah** [comment]
> We're working on the team section whitespace by converting everything to png so its smaller/quicker to load.

We should use https://tinypng.com/ on pngs
Also there are ways to minify svgs as well (reduce the decimal points)

**Comment by ianmah** [comment]
@jvssicawu next time you should make 5 issues so you can increase your gh contribs

**Comment by jvssicawu** [comment]
@ianmah LMMFFAOOO yo man i aint about that life
