### ISSUE TITLE
'Required' error appearing erroneously (pg 3)

### ISSUE THREAD

**Issue by luceliu** [nwplus/nwhacks2020#38]
![image](https://user-images.githubusercontent.com/20194766/69025778-369c5b00-097d-11ea-8bf0-73aed204b06b.png)
Steps to reproduce
* Select 'Other' for "how did you hear about nwhacks" and type 'haha' in field that pops up
* Leaving some other fields empty/unchecked, try to Submit on last page
* Get correct errors
* Fill out all fields correctly and click Submit again
* Get 'Required' error on last checkbox

**Comment by luceliu** [comment]
'Other' might be broken:
![image](https://user-images.githubusercontent.com/20194766/69026074-47999c00-097e-11ea-9d49-863e2e823b5a.png)
BUT when i unchecked the last checkbox, then got an error from that, then checked it again and clicked submit, it went thru - i.e. the original 'Other' error resolved itself

**Comment by luceliu** [comment]
* Note I just reproduced it with the steps I outlined above, giulio you didn't follow them correctly lmao 
* The error only appears when you have 'Other' selected - if you change that dropdown to something else the form will submit 
* @kozr discovered that if you check the checkboxes backwards i.e. from bottom to top, the form submits. Seems like once you check the 3rd checkbox, both 'Required's from checkbox 3 and 4 disappear

**Comment by ianmah** [comment]
LOL this is a rip
