### ISSUE TITLE
'Take me back home' briefly shows application form with errors

### ISSUE THREAD

**Issue by luceliu** [nwplus/nwhacks2020#39]
Steps to reproduce
* Submit an application
* Click 'Take me back home'
* You'll see empty application form page 1 full of errors for 1-2 seconds before nwhacks homepage appears on screen

**Comment by Ciuffi** [comment]
Essentially this happens because I clear the store before routing to the new page, and the routing takes a second to load. We need to figure out a less obvious way to clear the store after the app has been submitted, without redirecting you to the start of the form again.
